openshift/descheduler

- pkg/descheduler/pod/pods.go
@ravisantoshgudimetla @ingvagabund @sjenning
During testing with latest origin, I noticed that after the PR https://github.com/openshift/origin/pull/19104 is merged, descheduler needs to be updated to make sure, critical pods are not exclusive to kube-system namespace but can now exist in openshift-* namespaces too. Without this PR, descheduler would evict critical pods in openshift-* namespaces.
> Update critical pods handling to openshift-* namespaces too.

- docs/release-guide.md
- kubernetes/cronjob.yaml
- kubernetes/job.yaml
- pkg/descheduler/evictions/evictions.go
Pulling https://github.com/kubernetes-sigs/descheduler/pull/287
> bug 1836971: Sync with upstream

- README.md
- charts/descheduler/Chart.yaml
- pkg/descheduler/descheduler.go
- pkg/descheduler/node/node.go
- pkg/descheduler/strategies/duplicates.go
- pkg/descheduler/strategies/lownodeutilization.go
- pkg/descheduler/strategies/node_affinity.go
- pkg/descheduler/strategies/node_taint.go
- pkg/descheduler/strategies/pod_antiaffinity.go
- pkg/descheduler/strategies/pod_antiaffinity_test.go
- pkg/descheduler/strategies/pod_lifetime.go
- pkg/descheduler/strategies/toomanyrestarts.go
- pkg/utils/pod.go
Pulls in upstream changes, notably https://github.com/kubernetes-sigs/descheduler/pull/395 which fixes the mentioned bug
> Bug 1877319: Move IsEvictable check in PodAntiAffinity

- .github/workflows/release.yaml
- README.md
- charts/descheduler/Chart.yaml
- charts/descheduler/README.md
- pkg/descheduler/strategies/lownodeutilization.go
Pull https://github.com/kubernetes-sigs/descheduler/pull/441 to resolve https://bugzilla.redhat.com/show_bug.cgi?id=1898134
> bug 1898134: Sync with upstream

- .travis.yml
To unblock https://github.com/openshift/descheduler/pull/60
> Bug 1949050: Bump Go to 1.16 in Travis

- images/descheduler/Dockerfile.rhel7
> Bump image to rhel-9

- Makefile
> NO-JIRA: No-op change to trigger a new image build

- .snyk
> OCPBUGS-26169: Add .snyk file to exclude vendor and ignore unit tests

- Makefile
> OCPBUGS-14042: Makefile: set upstream descheduler version

- .ci-operator.yaml
- .snyk
- Makefile
- images/descheduler/Dockerfile.rhel7
- tools/import-verifier/import-verifier.go
> NO-JIRA: Sync with master

- OWNERS
> NO-JIRA: OWNERS: fix component name

- OWNERS
> no-jira: Release 4.18

- .tekton/descheduler-4-18-pull-request.yaml
- .tekton/descheduler-4-18-push.yaml
> UPSTREAM: <carry>: [tekton]: build source image, hermetic builds, extend the list of archs

- Dockerfile
> no-jira: UPSTREAM: <carry>: Update Dockerfile for Konflux

- .tekton/descheduler-4-16-pull-request.yaml
- .tekton/descheduler-4-16-push.yaml
> no-jira: UPSTREAM: <carry>: [tekton]: build source image, hermetic builds, extend the list of archs

- .tekton/descheduler-4-18-pull-request.yaml
- .tekton/descheduler-4-18-push.yaml
- Dockerfile
- README.md
> Sync master with release 4.18

- README.md
> no-jira: UPSTREAM: <carry>: no-op: re-trigger pipeline

- README.md
> UPSTREAM: <carry>: no-op: re-trigger pipeline

- .tekton/descheduler-4-18-pull-request.yaml
- .tekton/descheduler-4-18-push.yaml
> UPSTREAM: <carry>: [tekton]: make the operator configs more up2date

- .tekton/descheduler-4-19-pull-request.yaml
- .tekton/descheduler-4-19-push.yaml
Applying https://github.com/openshift/descheduler/pull/170
> UPSTREAM: <carry>: bump(.tekton)=4.19

- README.md
> UPSTREAM: <drop>: re-trigger the pipeline

- .tekton/descheduler-4-18-pull-request.yaml
- .tekton/descheduler-4-18-push.yaml
> .tekton: Add missing params

- .tekton/descheduler-4-20-pull-request.yaml
- .tekton/descheduler-4-20-push.yaml
consolidate tekton pipelines. this commit adjusts the pr opened by konflux.
> UPSTREAM: <carry>: update tekton pipelines for release 4.20.

- .tekton/descheduler-4-20-pull-request.yaml
- .tekton/descheduler-4-20-push.yaml
> no-jira: UPSTREAM: <drop>: feat(.tekton): trigger pull/push runs only when relevant files/directories are changed
